server:
  port: 69

spring:
  application:
    name: glennmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: admin_product_route
          uri: lb://glennmall-product
          predicates:
            - Path=/glennmall_admin/product/**
          filters:
            - RewritePath=/glennmall_admin/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://glennmall-admin
          predicates:
            - Path=/glennmall_admin/**
#          filters:
#            - RewritePath=/glennmall_admin/(?<segment>.*),/glennmall_admin/$\{segment}