server:
  port: 4000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/glennmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: glennmall-product

mybatis-plus:
  type-aliases-package: com.glennmall.product.entity
  mapper-locations: classpath:com/glennmall/product/dao/mapper/*.xml
  #id自增
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
logging:
  level:
    com.glennmall.product: debug