server:
  port: 3000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/glennmall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: glennmall-order

mybatis-plus:
  type-aliases-package: com.glennmall.order.entity
  mapper-locations: classpath:com/glennmall/order/dao/mapper/*.xml
  #id自增
  global-config:
    db-config:
      id-type: auto

